sudo: required
language: python

services:
  - docker

matrix:
  include:
    - python: 3.6
      env: TOXENV=py36
    - python: 3.5
      env: TOXENV=py35
    - python: 3.4
      env: TOXENV=py34

install:
  - pip install -U tox

script:
  - tox

before_install:
  - docker pull docker.sunet.se/eduid/redis:latest
  - docker pull docker.sunet.se/eduid/mongodb:latest
  - pip install pytest-cov codecov -rrequirements.txt -rtests/requirements.txt .

after_success:
  - py.test tests/ --cov=./
  - codecov
